trigger:
- master

variables:
  buildConfiguration: 'Release'
  framework: 'net5.0'
  artifactName: 'stupid-todo'

stages:
  - stage: Build
    displayName: Build stage

    jobs:
      - job: Build
        displayName: Build
        pool:
            vmImage: 'windows-latest'

        steps:
        - task: UseDotNet@2
          displayName: Install .NET 5 SDK
          inputs:
            packageType: 'sdk'
            version: 5.x

        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: build
            projects: '**/*.sln'
            arguments: --configuration $(buildConfiguration)

        - task: DotNetCoreCLI@2
          displayName: Publish REST API
          inputs:
            command: publish
            projects: 'StupidTodo.WebApi/StupidTodo.WebApi.csproj'
            publishWebProjects: false
            zipAfterPublish: true
            arguments: --configuration $(buildConfiguration) --no-build --output $(build.ArtifactStagingDirectory) --framework $(framework)

        - task: PublishBuildArtifacts@1
          displayName: Upload Artifacts to Staging
          inputs:
            PathtoPublish: '$(build.ArtifactStagingDirectory)'
            ArtifactName: $(artifactName)
            Parallel: true

  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  
    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'Live'
      pool:
        vmImage: 'windows-latest'
  
        steps:
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy REST API (Azure Web App)'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure Stupid Todo'
            appType: 'webApp'
            WebAppName: 'stupidtodo'
            package: '$(Pipeline.Workspace)/$(artifactName)/StuidTod.WebApi.zip'
